### ISSUE TITLE
ti pointing system

### ISSUE THREAD

**Issue by alimusavi67** [ctyar/oracle#1]
how TI pointing system work

**Comment by alimusavi67** [comment]
- Two groups of nine teams
- Each match consists of two games against the same opponent
- A 2-0 win provides 2 points, 1-1 provides 1 point, and 0-2 provides 0 points
 If there is a tie along the Upper and Lower Bracket divider or between the lower bracket and elimination divider, more games will be played.
- For other games, the following is used:

1- Compare the matchup history of the tied teams
2- Compare their wins vs the seed right below them. Repeat until resolved.
3- Coin toss

**Comment by ctyar** [comment]
Nice job
